### ISSUE TITLE
Can you please add clear step by step how to use this node?

### ISSUE THREAD

**Issue by boygiandi** [bramkn/n8n-nodes-generate-report#1]
I installed this node and have no idea how to use it. I don't understand the Template key and Output key.. please help.
Thanks

**Comment by HomeBro** [comment]
I have also installed this node because it looked like something I could use in one of my Flows, but I really don't know how to use this node after installation.

Please help :)

**Comment by bramkn** [comment]
I have updated the readme with a little more info.
If you need more help please book a consult.

**Comment by bramkn** [comment]
Closing this ticket
