### ISSUE TITLE
Inserting an image (base64)

### ISSUE THREAD

**Issue by Hobby-Student** [bramkn/n8n-nodes-generate-report#3]
Hi @bramkn,

I'm trying to insert some images in a document. I run n8n in docker with libreoffice installed. So far everything works great, except images. I already opened an issue with easy-template-x. But perhaps there is something in n8n to take care of.

Do you have any idea, what I'm doing wrong?

EDIT, forgot the pictures:
![image](https://github.com/user-attachments/assets/01e33e7c-dcd1-4ca8-8765-8ccd04b6a4c5)

in code:
`{"_type":"image","format":"image/jpeg","source":{"type":"Buffer","data":[117,...,217]},"width":200,"height":200}`

Whenever I execute this, I get `Error: Binary type 'Object' is not supported.`

**Comment by bramkn** [comment]
Hi,

Sorry I have no idea and do not offer free support on the node or n8n.
